### ISSUE TITLE
"/undefined" appended to URL and page reloads repeatedly, causing crash

### ISSUE THREAD

**Issue by tab00** [timothyarmes/ta-meteor-apollo-starter-kit#3]
After signup,  loading the app from its root URL causes the above error.

If I delete browser localstorage, and load root URL, the problem no longer occurs, and I can re-login. Then if I load the root URL again the problem returns.

Please fix this problem.

**Comment by tab00** [comment]
I changed https://github.com/timothyarmes/ta-meteor-apollo-starter-kit/blob/7876625974725fbb10c2aeae5bda2069345a695d/app/intl/index.js#L19

to

`export const primaryLocale = 'en'`

which now prevents the problem from occuring.

**Comment by timothyarmes** [comment]
Defining a primaryLocale is intended for cases where you don't wish to have a locale prefix for the main language. For example, in your case the en locale will now be server at _localhost:3000/_ rather than _localhost:3000/en_.

Although then may have avoided the bug you're seeing, it's not really a solution.

I suspect that that is a conflict between the service worker and Meteor's hot code refresh. I've seen it myself but I can't yet figure out what's going on. For the time being you could remove the service worker registration and delete the service worker from your browser.

**Comment by timothyarmes** [comment]
Actually, this bug was unrelated to the service worker. It's now been fixed.

**Comment by timothyarmes** [comment]
Actually, this bug was unrelated to the service worker. It's now been fixed.

**Comment by timothyarmes** [comment]
Actually, this bug was unrelated to the service worker. It's now been fixed
